name: flutter_web_redirect
description: "A Flutter Web App integrated with Ory."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: 3.10.6
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_dotenv: ^6.0.0
  ory_client: ^1.20.11
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Load our env file from the root directory
  assets:
    - .env
