name: flutter_web_redirect
description: A Flutter Web App integrated with Ory.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^5.3.2
  flutter_dotenv: ^5.1.0
  ory_client: ^1.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  # Load our env file from the root directory
  assets:
    - env
